### ISSUE TITLE
MBG EnterNameDlg doesn't work on js

### ISSUE THREAD

**Issue by thearst3rd** [RandomityGuy/MBHaxe#11]
When attempting to enter a name in the MBG version of mbhaxe compiled for the web, it doesn't respond to text input.

I tried fixing this myself but comparing the code to master, I really can't see what's different that would cause this.

Quick demo with an input display to show the characters aren't being registered:

https://user-images.githubusercontent.com/7307599/218625030-adae54ee-d5de-4880-993e-baf2451da164.mp4

**Comment by RandomityGuy** [comment]
Fixed in https://github.com/RandomityGuy/MBHaxe/commit/2b337d9bb0e97215ca2fca17bf6baa2699ffa2e5
