### ISSUE TITLE
Respawning while entering teleporter does not lock the marble on the start pad

### ISSUE THREAD

**Issue by dflat2** [RandomityGuy/MBHaxe#16]
How to reproduce the bug:

+ Load any level with a teleporter on the Platinum version, eg. Beginner no. 8 Teleport Training
+ Enter the teleporter
+ Press backspace when the marble fades away
+ You are not locked on the start pad

**Comment by RandomityGuy** [comment]
Thanks for the report, apparently it is actually a crash for native version.
Fixed in: https://github.com/RandomityGuy/MBHaxe/commit/3a3345c4d31de91b136e3cffd26dfa07918dcb7f
Web version will be updated, native version update later on.
