### ISSUE TITLE
Gem Hunt doesn't end properly if marble is OOB when timer hits 0s

### ISSUE THREAD

**Issue by dflat2** [RandomityGuy/MBHaxe#18]
On Ultra, Gem Hunt doesn't end properly if the marble is out of bounds. It respawns but the End Dialog never shows up. You may reproduce the bug easily on King of the Marble by jumping off the ledge when the timer hits about 1-2 seconds left.

**Comment by RandomityGuy** [comment]
Fixed in https://github.com/RandomityGuy/MBHaxe/commit/a96c95d19105f7ab6b91112d4a8312de19a5bca5
Version 1.0.1 released with the bugfixes
