### ISSUE TITLE
Top score not saving in Gem Hunt

### ISSUE THREAD

**Issue by dflat2** [RandomityGuy/MBHaxe#19]
It looks like top scores aren't saved anymore in Gem Hunt since the update (I believe it was working in the previous version, can't remember). Are those lines supposed to be commented out in `EndGameGui.hx`.

```
// var myScore = {name: "Player", time: score};
// Settings.saveScore(mission.path, myScore, scoreType);
```

**Comment by RandomityGuy** [comment]
Yes, they have been moved to the touchFinish function in MarbleWorld.hx.
However I forgot to port it to the gem hunt class. Will fix.

**Comment by RandomityGuy** [comment]
Fixed in https://github.com/RandomityGuy/MBHaxe/commit/d6278b344531ea62f2e3d36a10a7f1185d4bb164
