### ISSUE TITLE
"Replays" button not working on Mac

### ISSUE THREAD

**Issue by dflat2** [RandomityGuy/MBHaxe#20]
In the main menu, clicking on "Replays" button doesn't do anything on the Desktop version (I'm on Mac OS Ventura 13.3.1). The button works in the web browser, it opens a file selection dialog as expected.

This bug applies to all mods, Gold, Platinum and Ultra.

**Comment by RandomityGuy** [comment]
Try creating data/replays folder in ~/Library/Application Support/MBHaxe-MB[G/P/U] so that the path to replays folder is
~/Library/Application Support/MBHaxe-MB[G/P/U]/data/replays and see if that works?

**Comment by dflat2** [comment]
The folder `data/replays` has already been automatically created from the game when the first replay was recorded. Whether the folder is there or not, the "Replays" button doesn't do anything on the desktop version. It's supposed to load the `ReplayCenterGui` right? Does it work on Windows? I don't see anything in the code that could make it work on Windows but not Mac.

**Comment by RandomityGuy** [comment]
Apparently the function I was using just doesn't work outside of the .app filesystem.
Fixed in https://github.com/RandomityGuy/MBHaxe/commit/4f23c2cea954b1cd5e20ad0f17fbdadd1fb26c7d
Download the updated versions from the same link as latest version. Version number is still the same.
