### ISSUE TITLE
[MBHaxe Ultra] Blast particles persists after rewind

### ISSUE THREAD

**Issue by dflat2** [RandomityGuy/MBHaxe#22]
When using blast and then rewinding before the blast, the blast particles are still emitted at the same time (but it's just an issue with the particles -- there's no blast applied to the marble and the blast reload bar is behaving as expected).

**Comment by RandomityGuy** [comment]
Known issue, visual only as you said.

**Comment by RandomityGuy** [comment]
Fixed in https://github.com/RandomityGuy/MBHaxe/commit/1e4550527e68bd0398700eab54d22d45716933fe
Web version updated.
Native versions later.
