### ISSUE TITLE
[Web] [Manifest] Manifest fixes

### ISSUE THREAD

**Issue by glitch128** [RandomityGuy/MBHaxe#26]
make manifests different for all three versions as MBU is the only one with a manifest, but it shows itself as MBG, and MBG and MBP don't have manifests linked. what I would suggest is making 2 new manifest files and naming them `manifest-gold.json` and `manifest-platinum.json` respectively, and renaming `manifest.json` at `/data/manifest.json` to `manifest-ultra.json` and changing the code of the manifests to 
```json
{
	"name": "Marble Blast Gold Haxe Port",
	"short_name": "Marble Blast Gold",
	"description": "A reimplementation of Marble Blast Gold in Haxe",
	"dir": "ltr",
	"start_url": "/index.html?app=true",
	"scope": "/",
	"display": "fullscreen",
	"orientation": "landscape",
	"background_color": "black",
	"theme_color": "black",
	"categories": [
		"games"
	],
	"lang": "en-US",
	"icons": [
		{
			"src": "/data/icons/icon-512.png",
			"type": "image/png",
			"sizes": "512x512"
		},
		{
			"src": "/data/icons/icon-256.png",
			"type": "image/png",
			"sizes": "256x256"
		},
		{
			"src": "/data/icons/icon-192.png",
			"type": "image/png",
			"sizes": "192x192"
		},
		{
			"src": "/data/icons/icon-180.png",
			"type": "image/png",
			"sizes": "180x180"
		},
		{
			"src": "/data/icons/icon-144.png",
			"type": "image/png",
			"sizes": "144x144"
		},
		{
			"src": "/data/icons/icon-128.png",
			"type": "image/png",
			"sizes": "128x128"
		},
		{
			"src": "/data/icons/icon-96.png",
			"type": "image/png",
			"sizes": "96x96"
		},
		{
			"src": "/data/icons/icon-64.png",
			"type": "image/png",
			"sizes": "64x64"
		},
		{
			"src": "/data/icons/icon-48.png",
			"type": "image/png",
			"sizes": "48x48"
		},
		{
			"src": "/data/icons/icon-32.png",
			"type": "image/png",
			"sizes": "32x32"
		}
	]
}
```
for `manifest-gold.json`
```json
{
	"name": "Marble Blast Ultra Haxe Port",
	"short_name": "Marble Blast Ultra",
	"description": "A reimplementation of Marble Blast Ultra in Haxe",
	"dir": "ltr",
	"start_url": "/index.html?app=true",
	"scope": "/",
	"display": "fullscreen",
	"orientation": "landscape",
	"background_color": "black",
	"theme_color": "black",
	"categories": [
		"games"
	],
	"lang": "en-US",
	"icons": [
		{
			"src": "/data/icons/icon-512.png",
			"type": "image/png",
			"sizes": "512x512"
		},
		{
			"src": "/data/icons/icon-256.png",
			"type": "image/png",
			"sizes": "256x256"
		},
		{
			"src": "/data/icons/icon-192.png",
			"type": "image/png",
			"sizes": "192x192"
		},
		{
			"src": "/data/icons/icon-180.png",
			"type": "image/png",
			"sizes": "180x180"
		},
		{
			"src": "/data/icons/icon-144.png",
			"type": "image/png",
			"sizes": "144x144"
		},
		{
			"src": "/data/icons/icon-128.png",
			"type": "image/png",
			"sizes": "128x128"
		},
		{
			"src": "/data/icons/icon-96.png",
			"type": "image/png",
			"sizes": "96x96"
		},
		{
			"src": "/data/icons/icon-64.png",
			"type": "image/png",
			"sizes": "64x64"
		},
		{
			"src": "/data/icons/icon-48.png",
			"type": "image/png",
			"sizes": "48x48"
		},
		{
			"src": "/data/icons/icon-32.png",
			"type": "image/png",
			"sizes": "32x32"
		}
	]
}
```
for `manifest-ultra.json`, and 
```json
{
	"name": "Marble Blast Platinum Haxe Port",
	"short_name": "Marble Blast Platinum",
	"description": "A reimplementation of Marble Blast Platinum in Haxe",
	"dir": "ltr",
	"start_url": "/index.html?app=true",
	"scope": "/",
	"display": "fullscreen",
	"orientation": "landscape",
	"background_color": "black",
	"theme_color": "black",
	"categories": [
		"games"
	],
	"lang": "en-US",
	"icons": [
		{
			"src": "/data/icons/icon-512.png",
			"type": "image/png",
			"sizes": "512x512"
		},
		{
			"src": "/data/icons/icon-256.png",
			"type": "image/png",
			"sizes": "256x256"
		},
		{
			"src": "/data/icons/icon-192.png",
			"type": "image/png",
			"sizes": "192x192"
		},
		{
			"src": "/data/icons/icon-180.png",
			"type": "image/png",
			"sizes": "180x180"
		},
		{
			"src": "/data/icons/icon-144.png",
			"type": "image/png",
			"sizes": "144x144"
		},
		{
			"src": "/data/icons/icon-128.png",
			"type": "image/png",
			"sizes": "128x128"
		},
		{
			"src": "/data/icons/icon-96.png",
			"type": "image/png",
			"sizes": "96x96"
		},
		{
			"src": "/data/icons/icon-64.png",
			"type": "image/png",
			"sizes": "64x64"
		},
		{
			"src": "/data/icons/icon-48.png",
			"type": "image/png",
			"sizes": "48x48"
		},
		{
			"src": "/data/icons/icon-32.png",
			"type": "image/png",
			"sizes": "32x32"
		}
	]
}
```
for `manifest-platinum.json`
and use these images for the corresponding games
Platinum:
![icon-32x32](https://github.com/RandomityGuy/MBHaxe/assets/78228404/ed0e2c16-811d-408c-8bf2-91594a907bb1)![icon-48x48](https://github.com/RandomityGuy/MBHaxe/assets/78228404/1bda26a5-a84c-4856-b30e-a392b1d6ad2e)![icon-64x64](https://github.com/RandomityGuy/MBHaxe/assets/78228404/4da59f54-8576-4fdb-94d7-f41b3f882316)![icon-96x96](https://github.com/RandomityGuy/MBHaxe/assets/78228404/29660c1f-7e7b-48fc-8f66-8e0517adef59)![icon-128x128](https://github.com/RandomityGuy/MBHaxe/assets/78228404/33f082d7-b0ba-4346-ab42-a8610845f487)![icon-144x144](https://github.com/RandomityGuy/MBHaxe/assets/78228404/183888ab-62b5-426d-a4bb-8f6ec0e3703f)![icon-180x180](https://github.com/RandomityGuy/MBHaxe/assets/78228404/096a25e8-6b2c-4cf7-a2f4-1ecdf0b5b608)![icon-192x192](https://github.com/RandomityGuy/MBHaxe/assets/78228404/e5500bb1-68d5-449d-b164-020a6dabf7ca)![icon-256x256](https://github.com/RandomityGuy/MBHaxe/assets/78228404/33ca9bdb-513d-4114-9868-ddd191c0d2da)![icon-512x512](https://github.com/RandomityGuy/MBHaxe/assets/78228404/02334108-f90b-462f-b573-b68fd925febc)
Ultra:
![icon-32x32](https://github.com/RandomityGuy/MBHaxe/assets/78228404/6b791c3f-6028-4a78-9277-38cda604c559)![icon-48x48](https://github.com/RandomityGuy/MBHaxe/assets/78228404/dd892419-f5fd-4541-a93d-2734e563a959)![icon-64x64](https://github.com/RandomityGuy/MBHaxe/assets/78228404/97b2d71f-5edc-4cc8-aa67-5c4e4f83d786)![icon-96x96](https://github.com/RandomityGuy/MBHaxe/assets/78228404/1eafbc4f-9543-4f11-8680-c3840c3a3baf)![icon-128x128](https://github.com/RandomityGuy/MBHaxe/assets/78228404/59f92cfc-ac9c-4d9d-b0ae-be4fb55ee6e0)![icon-144x144](https://github.com/RandomityGuy/MBHaxe/assets/78228404/6eb22d60-696f-40fb-9bd5-cdda21f48693)![icon-180x180](https://github.com/RandomityGuy/MBHaxe/assets/78228404/6a8587a9-84a8-49c5-8d37-206e6d481ad0)![icon-192x192](https://github.com/RandomityGuy/MBHaxe/assets/78228404/957d028c-9b93-49e1-84f2-05fdaf80927e)![icon-256x256](https://github.com/RandomityGuy/MBHaxe/assets/78228404/72be5b3e-cd94-4131-a684-3f719e6a3673)![icon-512x512](https://github.com/RandomityGuy/MBHaxe/assets/78228404/162589a3-433c-4069-bff4-64e5865c4a5e)

**Comment by RandomityGuy** [comment]
Sure. Initially when I added the manifests, they weren't quite working but seems like they do work now.
Can you do the PRs for these changes?

**Comment by glitch128** [comment]
Actually, I'm trying to make a pull request, but how old are the index.html files on the https://marbleblast[ gold | NULL | ultra ].randomityguy.me sites?
Here are the .zip files with the manifests inlcuded.
[platinum.zip](https://github.com/RandomityGuy/MBHaxe/files/13650756/platinum.zip)
[ultra.zip](https://github.com/RandomityGuy/MBHaxe/files/13650759/ultra.zip)

**Comment by RandomityGuy** [comment]
Yeah those index.html files are slightly different from the ones in the repo, causing them to not be in the same VCS.
Fixed those files on the server, changes will be propagated as cache invalidates.
Merged the PRs, thanks.
