### ISSUE TITLE
make a 3ds port of this

### ISSUE THREAD

**Issue by Android986player** [RandomityGuy/MBHaxe#34]
thats literally it

**Comment by Android986player** [comment]
and make a web port too

**Comment by RandomityGuy** [comment]
The framework this game runs on cannot be compiled for 3ds.
The game is already available for web on the following links:
Platinum: https://marbleblast.randomityguy.me
Gold: https://marbleblastgold.randomityguy.me
Ultra: https://marbleblastultra.randomityguy.me
