### ISSUE TITLE
mbu android mbg android not working on amazon fire tablet

### ISSUE THREAD

**Issue by Android986player** [RandomityGuy/MBHaxe#40]

**Comment by Android986player** [comment]
mbu makes it to the garage games logo before crashing and mbg lets you choose a level but as soon as you choose a level it crashes

**Comment by RandomityGuy** [comment]
Can you let me know what the model of the tablet is?

**Comment by Android986player** [comment]
i did not check and i do not think its from 2019 ithink 2017

**Comment by RandomityGuy** [comment]
Then it does not meet the minimum requirements to run.
https://developer.amazon.com/docs/fire-tablets/ft-device-specifications-fire-models.html?v=firehd7_2017
OpenGL version needs to atleast ES 3.0

**Comment by Android986player** [comment]
how do i get it?

**Comment by RandomityGuy** [comment]
It is hardware specific, you need a newer device.

**Comment by Android986player** [comment]
ok
