### ISSUE TITLE
[Android] [Controller Support] Controllers aren't working as intended in ultra native.

### ISSUE THREAD

**Issue by glitch128** [RandomityGuy/MBHaxe#41]
Only the A and B buttons work
Tested with hori pad Xbox and razer fishing v1 and NX Pro Controller has Dpad

**Comment by RandomityGuy** [comment]
Turns out android build used an old version of SDL. Will be fixed in next version.

**Comment by RandomityGuy** [comment]
Fixed in MBU 1.1.1

**Comment by glitch128** [comment]
confirmed to be fixed👍
