### ISSUE TITLE
stuck in 40mb on gold, 200mb on platinum and needs authorization in different browser

### ISSUE THREAD

**Issue by m1chip10** [RandomityGuy/MBHaxe#42]
cant even download marble blast gold, platinum and ultra apk file in google chrome, via browser and opera mini :(.
just simply says needs authorization (google chrome), 401: unauthorized (via browser) and access denied (opera mini). please can someone authorize this

**Comment by RandomityGuy** [comment]
Try downloading the apk

**Comment by RandomityGuy** [comment]
This is a Github specific issue which isn't really under my control.
