### ISSUE TITLE
compile request

### ISSUE THREAD

**Issue by Android986player** [RandomityGuy/MBHaxe#48]
I was wondering if someone could compile this into a single HTML file for offline use I would prefer mbu to be a single HTML file

**Comment by RandomityGuy** [comment]
[Download](https://github.com/RandomityGuy/MBHaxe/releases/tag/1.6.1) the game

**Comment by Android986player** [comment]
I downloaded the source code bcuz I'm on chrome os but when I open index.html all I see is a black screen

**Comment by RandomityGuy** [comment]
Follow these instructions in the video to run windows apps:
https://youtu.be/Egp2BosUaWg
If that doesn't work, download the site using
https://saveweb2zip.com/en
Now copy the data folder from the source code that yoy downloaded and merge it with the data folder of this site download.

**Comment by Android986player** [comment]
it didn't work when I load the downloaded site with the data folder it stays stuck on loading ui

**Comment by RandomityGuy** [comment]
Seems like due to browser security restrictions. You need to host it on a [Web Server](https://michaelsprojects.wordpress.com/2015/10/02/how-to-host-a-web-server-on-a-chromebook-without-linux-step-by-step-guide/)

**Comment by Android986player** [comment]
im on a school chromebook this app is blocked by the admins

**Comment by RandomityGuy** [comment]
Then unfortunately there isn't much I can do. All it needs is a server that you can run locally to get around the browser security issues that arise when you run it without a web server.
