### ISSUE TITLE
port questions. (not an issue just a question)

### ISSUE THREAD

**Issue by Fayaabitster** [RandomityGuy/MBHaxe#49]
would it be possible to port this to the PS3? i have a modded PS3 slim so id be completely viable to beta test it.
maybe even Roku too though that sounds a bit dumb.

**Comment by RandomityGuy** [comment]
Unfortunately the libraries and runtime used do not have a PS3 target, nor a Roku target. There is support for the newer consoles but it's locked behind the requirement of having the developer access and SDK to the platforms, as it is only after that procedure the original devs of the framework used are willing to share the console version of it.

**Comment by Fayaabitster** [comment]
that makes alot of sense and it would'nt make much sense to rewrite it all just for one console
